// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sol_denka_stockmanagement.Database;

#nullable disable

namespace sol_denka_stockmanagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251204013615_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("sol_denka_stockmanagement.Database.LedgerItem", b =>
                {
                    b.Property<int>("LedgerItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInStock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Length")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MisrollReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpecificGravity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Thickness")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Weight")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WinderInfo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LedgerItemId");

                    b.ToTable("LedgerItems");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Epc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LedgerItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TagId");

                    b.HasIndex("Epc")
                        .IsUnique();

                    b.HasIndex("LedgerItemId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.Tag", b =>
                {
                    b.HasOne("sol_denka_stockmanagement.Database.LedgerItem", "LedgerItem")
                        .WithMany("Tags")
                        .HasForeignKey("LedgerItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LedgerItem");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.LedgerItem", b =>
                {
                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
