// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sol_denka_stockmanagement.Database;

#nullable disable

namespace sol_denka_stockmanagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251204050107_AddInventoryResultType")]
    partial class AddInventoryResultType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("sol_denka_stockmanagement.Database.InventoryResult", b =>
                {
                    b.Property<int>("Inventory_result_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Inventory_result_type_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Inventory_sesstion_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Scanned_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("System_is_in_stock_at_scan")
                        .HasColumnType("INTEGER");

                    b.Property<int>("System_location_id_at_scan")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tag_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ledger_item_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Inventory_result_id");

                    b.HasIndex("Inventory_result_type_id");

                    b.HasIndex("Tag_id");

                    b.ToTable("InventoryResults");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.InventoryResultType", b =>
                {
                    b.Property<int>("Inventory_result_type_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Created_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Inventory_result_code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Inventory_result_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Is_active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Updated_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Inventory_result_type_id");

                    b.HasIndex("Inventory_result_code")
                        .IsUnique();

                    b.ToTable("InventoryResultTypes");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.LedgerItem", b =>
                {
                    b.Property<int>("Ledger_item_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Created_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Is_active")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Is_in_stock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Item_type_id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Length")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Location_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Misroll_reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Specific_gravity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Thickness")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Updated_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Weight")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Winder_info")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Ledger_item_id");

                    b.ToTable("LedgerItems");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.Tag", b =>
                {
                    b.Property<int>("Tag_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Created_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Epc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Is_active")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Ledger_item_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Updated_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Tag_id");

                    b.HasIndex("Epc")
                        .IsUnique();

                    b.HasIndex("Ledger_item_id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.InventoryResult", b =>
                {
                    b.HasOne("sol_denka_stockmanagement.Database.InventoryResultType", "InventoryResultType")
                        .WithMany("InventoryResults")
                        .HasForeignKey("Inventory_result_type_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("sol_denka_stockmanagement.Database.Tag", "Tag")
                        .WithMany("InventoryResults")
                        .HasForeignKey("Tag_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InventoryResultType");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.Tag", b =>
                {
                    b.HasOne("sol_denka_stockmanagement.Database.LedgerItem", "LedgerItem")
                        .WithMany("Tags")
                        .HasForeignKey("Ledger_item_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LedgerItem");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.InventoryResultType", b =>
                {
                    b.Navigation("InventoryResults");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.LedgerItem", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.Tag", b =>
                {
                    b.Navigation("InventoryResults");
                });
#pragma warning restore 612, 618
        }
    }
}
