// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sol_denka_stockmanagement.Database;

#nullable disable

namespace sol_denka_stockmanagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251204082846_AddItemType")]
    partial class AddItemType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("sol_denka_stockmanagement.Database.InventoryResult", b =>
                {
                    b.Property<int>("Inventory_result_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Inventory_result_type_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Inventory_session_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ledger_item_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Scanned_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("System_is_in_stock_at_scan")
                        .HasColumnType("INTEGER");

                    b.Property<int>("System_location_id_at_scan")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tag_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Inventory_result_id");

                    b.HasIndex("Inventory_result_type_id");

                    b.HasIndex("Inventory_session_id");

                    b.HasIndex("Ledger_item_id");

                    b.HasIndex("System_location_id_at_scan");

                    b.HasIndex("Tag_id");

                    b.ToTable("InventoryResults");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.InventoryResultType", b =>
                {
                    b.Property<int>("Inventory_result_type_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Created_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Inventory_result_code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Inventory_result_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Is_active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Updated_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Inventory_result_type_id");

                    b.ToTable("InventoryResultTypes");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.InventorySession", b =>
                {
                    b.Property<int>("Inventory_session_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Device_id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Executed_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Location_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Inventory_session_id");

                    b.HasIndex("Location_id");

                    b.ToTable("InventorySessions");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.ItemType", b =>
                {
                    b.Property<int>("Item_type_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Created_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Is_active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Item_type_code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Item_type_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Item_unit_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Updated_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Item_type_id");

                    b.HasIndex("Item_type_code")
                        .IsUnique();

                    b.ToTable("ItemTypes");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.LedgerItem", b =>
                {
                    b.Property<int>("Ledger_item_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Created_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Is_active")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Is_in_stock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Item_type_id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Length")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Location_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Misroll_reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Specific_gravity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Thickness")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Updated_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Weight")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Winder_info")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Ledger_item_id");

                    b.HasIndex("Item_type_id");

                    b.HasIndex("Location_id");

                    b.ToTable("LedgerItems");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.Location", b =>
                {
                    b.Property<int>("Location_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Created_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Is_active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location_code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Updated_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Location_id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.Stock", b =>
                {
                    b.Property<int>("Stock_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Created_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Item_type_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Location_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Total_quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Updated_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Stock_id");

                    b.HasIndex("Item_type_id");

                    b.HasIndex("Location_id");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.Tag", b =>
                {
                    b.Property<int>("Tag_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Created_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Epc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Is_active")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Ledger_item_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Updated_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Tag_id");

                    b.HasIndex("Epc")
                        .IsUnique();

                    b.HasIndex("Ledger_item_id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.TagActionType", b =>
                {
                    b.Property<int>("Tag_action_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action_code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Created_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Is_active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Updated_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Tag_action_id");

                    b.ToTable("TagActionTypes");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.TagHistory", b =>
                {
                    b.Property<int>("Tag_history_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Ledger_item_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Occured_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TagActionTypeTag_action_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tag_action_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tag_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Tag_history_id");

                    b.HasIndex("Ledger_item_id");

                    b.HasIndex("TagActionTypeTag_action_id");

                    b.HasIndex("Tag_action_id");

                    b.HasIndex("Tag_id");

                    b.ToTable("TagHistories");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.InventoryResult", b =>
                {
                    b.HasOne("sol_denka_stockmanagement.Database.InventoryResultType", "InventoryResultType")
                        .WithMany("InventoryResults")
                        .HasForeignKey("Inventory_result_type_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("sol_denka_stockmanagement.Database.InventorySession", "InventorySession")
                        .WithMany("InventoryResults")
                        .HasForeignKey("Inventory_session_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sol_denka_stockmanagement.Database.LedgerItem", "LedgerItem")
                        .WithMany("InventoryResults")
                        .HasForeignKey("Ledger_item_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("sol_denka_stockmanagement.Database.Location", "Location")
                        .WithMany("InventoryResults")
                        .HasForeignKey("System_location_id_at_scan")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("sol_denka_stockmanagement.Database.Tag", "Tag")
                        .WithMany("InventoryResults")
                        .HasForeignKey("Tag_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InventoryResultType");

                    b.Navigation("InventorySession");

                    b.Navigation("LedgerItem");

                    b.Navigation("Location");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.InventorySession", b =>
                {
                    b.HasOne("sol_denka_stockmanagement.Database.Location", "Location")
                        .WithMany("InventorySessions")
                        .HasForeignKey("Location_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.LedgerItem", b =>
                {
                    b.HasOne("sol_denka_stockmanagement.Database.ItemType", "ItemType")
                        .WithMany("LedgerItems")
                        .HasForeignKey("Item_type_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("sol_denka_stockmanagement.Database.Location", "Location")
                        .WithMany("LedgerItems")
                        .HasForeignKey("Location_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ItemType");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.Stock", b =>
                {
                    b.HasOne("sol_denka_stockmanagement.Database.ItemType", "ItemType")
                        .WithMany("Stocks")
                        .HasForeignKey("Item_type_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("sol_denka_stockmanagement.Database.Location", "Location")
                        .WithMany("Stocks")
                        .HasForeignKey("Location_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ItemType");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.Tag", b =>
                {
                    b.HasOne("sol_denka_stockmanagement.Database.LedgerItem", "LedgerItem")
                        .WithMany("Tags")
                        .HasForeignKey("Ledger_item_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LedgerItem");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.TagHistory", b =>
                {
                    b.HasOne("sol_denka_stockmanagement.Database.LedgerItem", "LedgerItem")
                        .WithMany("TagHistories")
                        .HasForeignKey("Ledger_item_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("sol_denka_stockmanagement.Database.TagActionType", null)
                        .WithMany("TagHistories")
                        .HasForeignKey("TagActionTypeTag_action_id");

                    b.HasOne("sol_denka_stockmanagement.Database.TagActionType", "TagActionType")
                        .WithMany()
                        .HasForeignKey("Tag_action_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("sol_denka_stockmanagement.Database.Tag", "Tag")
                        .WithMany("TagHistories")
                        .HasForeignKey("Tag_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LedgerItem");

                    b.Navigation("Tag");

                    b.Navigation("TagActionType");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.InventoryResultType", b =>
                {
                    b.Navigation("InventoryResults");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.InventorySession", b =>
                {
                    b.Navigation("InventoryResults");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.ItemType", b =>
                {
                    b.Navigation("LedgerItems");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.LedgerItem", b =>
                {
                    b.Navigation("InventoryResults");

                    b.Navigation("TagHistories");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.Location", b =>
                {
                    b.Navigation("InventoryResults");

                    b.Navigation("InventorySessions");

                    b.Navigation("LedgerItems");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.Tag", b =>
                {
                    b.Navigation("InventoryResults");

                    b.Navigation("TagHistories");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.TagActionType", b =>
                {
                    b.Navigation("TagHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
