// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sol_denka_stockmanagement.Database;

#nullable disable

namespace sol_denka_stockmanagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251212142526_SeedFieldMasterData2")]
    partial class SeedFieldMasterData2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("sol_denka_stockmanagement.Database.CsvHistory", b =>
                {
                    b.Property<int>("Csv_history_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Csv_task_type_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Device_id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Error_message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Executed_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("File_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Recode_num")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Csv_history_id");

                    b.HasIndex("Csv_task_type_id");

                    b.ToTable("CsvHistories");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.CsvTaskType", b =>
                {
                    b.Property<int>("Csv_task_type_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Created_at")
                        .HasColumnType("TEXT");

                    b.Property<string>("Csv_task_code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Csv_task_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Updated_at")
                        .HasColumnType("TEXT");

                    b.HasKey("Csv_task_type_id");

                    b.ToTable("CsvTaskTypes");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.EventType", b =>
                {
                    b.Property<int>("Event_type_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Created_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Event_code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Event_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Is_active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Updated_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Event_type_id");

                    b.ToTable("EventTypes");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.FieldMaster", b =>
                {
                    b.Property<int>("Field_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Control_type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Created_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Data_type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Field_code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Field_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Is_active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Updated_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Field_id");

                    b.ToTable("FieldMaster");

                    b.HasData(
                        new
                        {
                            Field_id = 1,
                            Control_type = "INPUT",
                            Created_at = "2025-01-01",
                            Data_type = "NUMBER",
                            Field_code = "WEIGHT",
                            Field_name = "重量",
                            Is_active = 1,
                            Updated_at = "2025-01-01"
                        },
                        new
                        {
                            Field_id = 2,
                            Control_type = "INPUT",
                            Created_at = "2025-01-01",
                            Data_type = "NUMBER",
                            Field_code = "LENGTH",
                            Field_name = "長さ",
                            Is_active = 1,
                            Updated_at = "2025-01-01"
                        },
                        new
                        {
                            Field_id = 3,
                            Control_type = "INPUT",
                            Created_at = "2025-01-01",
                            Data_type = "NUMBER",
                            Field_code = "THICKNESS",
                            Field_name = "厚さ",
                            Is_active = 1,
                            Updated_at = "2025-01-01"
                        },
                        new
                        {
                            Field_id = 4,
                            Control_type = "INPUT",
                            Created_at = "2025-01-01",
                            Data_type = "NUMBER",
                            Field_code = "WIDTH",
                            Field_name = "巾",
                            Is_active = 1,
                            Updated_at = "2025-01-01"
                        },
                        new
                        {
                            Field_id = 5,
                            Control_type = "INPUT",
                            Created_at = "2025-01-01",
                            Data_type = "NUMBER",
                            Field_code = "QUANTITY",
                            Field_name = "数量",
                            Is_active = 1,
                            Updated_at = "2025-01-01"
                        },
                        new
                        {
                            Field_id = 6,
                            Control_type = "DROPDOWN",
                            Created_at = "2025-01-01",
                            Data_type = "TEXT",
                            Field_code = "WINDER",
                            Field_name = "巻取機",
                            Is_active = 1,
                            Updated_at = "2025-01-01"
                        },
                        new
                        {
                            Field_id = 7,
                            Control_type = "INPUT",
                            Created_at = "2025-01-01",
                            Data_type = "TEXT",
                            Field_code = "OCCURRENCE_REASON",
                            Field_name = "発生理由",
                            Is_active = 1,
                            Updated_at = "2025-01-01"
                        },
                        new
                        {
                            Field_id = 8,
                            Control_type = "INPUT",
                            Created_at = "2025-01-01",
                            Data_type = "TEXT",
                            Field_code = "LOT_NO",
                            Field_name = "Lot No",
                            Is_active = 1,
                            Updated_at = "2025-01-01"
                        },
                        new
                        {
                            Field_id = 9,
                            Control_type = "DATETIME_PICKER",
                            Created_at = "2025-01-01",
                            Data_type = "DATETIME",
                            Field_code = "OCCURRED_AT",
                            Field_name = "発生日時",
                            Is_active = 1,
                            Updated_at = "2025-01-01"
                        },
                        new
                        {
                            Field_id = 10,
                            Control_type = "DATETIME_PICKER",
                            Created_at = "2025-01-01",
                            Data_type = "DATETIME",
                            Field_code = "PROCESSED_AT",
                            Field_name = "処理日時",
                            Is_active = 1,
                            Updated_at = "2025-01-01"
                        },
                        new
                        {
                            Field_id = 11,
                            Control_type = "DROPDOWN",
                            Created_at = "2025-01-01",
                            Data_type = "TEXT",
                            Field_code = "LOCATION",
                            Field_name = "保管場所",
                            Is_active = 1,
                            Updated_at = "2025-01-01"
                        });
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.InventoryResult", b =>
                {
                    b.Property<int>("Inventory_result_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Inventory_result_type_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Inventory_session_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LedgerItemEventEvent_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ledger_item_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Scanned_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("System_is_in_stock_at_scan")
                        .HasColumnType("INTEGER");

                    b.Property<int>("System_location_id_at_scan")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tag_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Inventory_result_id");

                    b.HasIndex("Inventory_result_type_id");

                    b.HasIndex("Inventory_session_id");

                    b.HasIndex("LedgerItemEventEvent_id");

                    b.HasIndex("Ledger_item_id");

                    b.HasIndex("System_location_id_at_scan");

                    b.HasIndex("Tag_id");

                    b.ToTable("InventoryResults");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.InventoryResultType", b =>
                {
                    b.Property<int>("Inventory_result_type_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Created_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Inventory_result_code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Inventory_result_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Is_active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Updated_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Inventory_result_type_id");

                    b.ToTable("InventoryResultTypes");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.InventorySession", b =>
                {
                    b.Property<int>("Inventory_session_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Device_id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Executed_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Location_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Inventory_session_id");

                    b.HasIndex("Location_id");

                    b.ToTable("InventorySessions");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.ItemType", b =>
                {
                    b.Property<int>("Item_type_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Created_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Is_active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Item_type_code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Item_type_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Item_unit_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Updated_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Item_type_id");

                    b.HasIndex("Item_type_code")
                        .IsUnique();

                    b.HasIndex("Item_unit_id");

                    b.ToTable("ItemTypes");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.ItemTypeFieldSetting", b =>
                {
                    b.Property<int>("Item_type_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Field_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Created_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Is_required")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Is_visible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Updated_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Item_type_id", "Field_id");

                    b.HasIndex("Field_id");

                    b.ToTable("ItemTypeFieldSettings");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.ItemUnit", b =>
                {
                    b.Property<int>("Item_unit_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Created_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Item_unit_code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Keyword")
                        .HasColumnType("TEXT");

                    b.Property<int>("Unit_category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Updated_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("item_unit_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Item_unit_id");

                    b.ToTable("ItemUnits");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.LedgerItem", b =>
                {
                    b.Property<int>("Ledger_item_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Created_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Is_active")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Is_in_stock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Item_type_id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Length")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Location_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Misroll_reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Specific_gravity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Thickness")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Updated_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Weight")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Winder_info")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Ledger_item_id");

                    b.HasIndex("Item_type_id");

                    b.HasIndex("Location_id");

                    b.ToTable("LedgerItems");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.LedgerItemEvent", b =>
                {
                    b.Property<int>("Event_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Event_type_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ledger_item_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Location_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Memo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Occurred_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Process_type_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Registered_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Event_id");

                    b.HasIndex("Event_type_id");

                    b.HasIndex("Ledger_item_id");

                    b.HasIndex("Process_type_id");

                    b.ToTable("LedgerItemEvents");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.Location", b =>
                {
                    b.Property<int>("Location_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Created_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Is_active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location_code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Updated_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Location_id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.ProcessType", b =>
                {
                    b.Property<int>("Process_type_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Created_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Is_active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Process_code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Process_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Updated_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Process_type_id");

                    b.ToTable("ProcessType");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.Stock", b =>
                {
                    b.Property<int>("Stock_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Created_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Item_type_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Location_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Total_quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Updated_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Stock_id");

                    b.HasIndex("Item_type_id");

                    b.HasIndex("Location_id");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.Tag", b =>
                {
                    b.Property<int>("Tag_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Created_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Epc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Is_active")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Ledger_item_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Updated_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Tag_id");

                    b.HasIndex("Epc")
                        .IsUnique();

                    b.HasIndex("Ledger_item_id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.TagActionType", b =>
                {
                    b.Property<int>("Tag_action_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action_code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Created_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Is_active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Updated_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Tag_action_id");

                    b.ToTable("TagActionTypes");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.TagHistory", b =>
                {
                    b.Property<int>("Tag_history_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Ledger_item_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Occured_at")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TagActionTypeTag_action_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tag_action_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tag_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Tag_history_id");

                    b.HasIndex("Ledger_item_id");

                    b.HasIndex("TagActionTypeTag_action_id");

                    b.HasIndex("Tag_action_id");

                    b.HasIndex("Tag_id");

                    b.ToTable("TagHistories");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.CsvHistory", b =>
                {
                    b.HasOne("sol_denka_stockmanagement.Database.CsvTaskType", "CsvTaskType")
                        .WithMany("CsvHistory")
                        .HasForeignKey("Csv_task_type_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CsvTaskType");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.InventoryResult", b =>
                {
                    b.HasOne("sol_denka_stockmanagement.Database.InventoryResultType", "InventoryResultType")
                        .WithMany("InventoryResults")
                        .HasForeignKey("Inventory_result_type_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("sol_denka_stockmanagement.Database.InventorySession", "InventorySession")
                        .WithMany("InventoryResults")
                        .HasForeignKey("Inventory_session_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sol_denka_stockmanagement.Database.LedgerItemEvent", "LedgerItemEvent")
                        .WithMany()
                        .HasForeignKey("LedgerItemEventEvent_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sol_denka_stockmanagement.Database.LedgerItem", "LedgerItem")
                        .WithMany("InventoryResults")
                        .HasForeignKey("Ledger_item_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("sol_denka_stockmanagement.Database.Location", "Location")
                        .WithMany("InventoryResults")
                        .HasForeignKey("System_location_id_at_scan")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("sol_denka_stockmanagement.Database.Tag", "Tag")
                        .WithMany("InventoryResults")
                        .HasForeignKey("Tag_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InventoryResultType");

                    b.Navigation("InventorySession");

                    b.Navigation("LedgerItem");

                    b.Navigation("LedgerItemEvent");

                    b.Navigation("Location");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.InventorySession", b =>
                {
                    b.HasOne("sol_denka_stockmanagement.Database.Location", "Location")
                        .WithMany("InventorySessions")
                        .HasForeignKey("Location_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.ItemType", b =>
                {
                    b.HasOne("sol_denka_stockmanagement.Database.ItemUnit", "ItemUnit")
                        .WithMany("ItemTypes")
                        .HasForeignKey("Item_unit_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ItemUnit");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.ItemTypeFieldSetting", b =>
                {
                    b.HasOne("sol_denka_stockmanagement.Database.FieldMaster", "FieldMaster")
                        .WithMany("ItemTypeFieldSettings")
                        .HasForeignKey("Field_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("sol_denka_stockmanagement.Database.ItemType", "ItemType")
                        .WithMany("ItemTypeFieldSettings")
                        .HasForeignKey("Item_type_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FieldMaster");

                    b.Navigation("ItemType");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.LedgerItem", b =>
                {
                    b.HasOne("sol_denka_stockmanagement.Database.ItemType", "ItemType")
                        .WithMany("LedgerItems")
                        .HasForeignKey("Item_type_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("sol_denka_stockmanagement.Database.Location", "Location")
                        .WithMany("LedgerItems")
                        .HasForeignKey("Location_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ItemType");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.LedgerItemEvent", b =>
                {
                    b.HasOne("sol_denka_stockmanagement.Database.EventType", "EventType")
                        .WithMany("LedgerItemEvent")
                        .HasForeignKey("Event_type_id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("sol_denka_stockmanagement.Database.LedgerItem", "LedgerItem")
                        .WithMany("LedgerItemEvent")
                        .HasForeignKey("Ledger_item_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("sol_denka_stockmanagement.Database.ProcessType", "ProcessType")
                        .WithMany("LedgerItemEvent")
                        .HasForeignKey("Process_type_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EventType");

                    b.Navigation("LedgerItem");

                    b.Navigation("ProcessType");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.Stock", b =>
                {
                    b.HasOne("sol_denka_stockmanagement.Database.ItemType", "ItemType")
                        .WithMany("Stocks")
                        .HasForeignKey("Item_type_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("sol_denka_stockmanagement.Database.Location", "Location")
                        .WithMany("Stocks")
                        .HasForeignKey("Location_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ItemType");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.Tag", b =>
                {
                    b.HasOne("sol_denka_stockmanagement.Database.LedgerItem", "LedgerItem")
                        .WithMany("Tags")
                        .HasForeignKey("Ledger_item_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LedgerItem");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.TagHistory", b =>
                {
                    b.HasOne("sol_denka_stockmanagement.Database.LedgerItem", "LedgerItem")
                        .WithMany("TagHistories")
                        .HasForeignKey("Ledger_item_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("sol_denka_stockmanagement.Database.TagActionType", null)
                        .WithMany("TagHistories")
                        .HasForeignKey("TagActionTypeTag_action_id");

                    b.HasOne("sol_denka_stockmanagement.Database.TagActionType", "TagActionType")
                        .WithMany()
                        .HasForeignKey("Tag_action_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("sol_denka_stockmanagement.Database.Tag", "Tag")
                        .WithMany("TagHistories")
                        .HasForeignKey("Tag_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LedgerItem");

                    b.Navigation("Tag");

                    b.Navigation("TagActionType");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.CsvTaskType", b =>
                {
                    b.Navigation("CsvHistory");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.EventType", b =>
                {
                    b.Navigation("LedgerItemEvent");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.FieldMaster", b =>
                {
                    b.Navigation("ItemTypeFieldSettings");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.InventoryResultType", b =>
                {
                    b.Navigation("InventoryResults");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.InventorySession", b =>
                {
                    b.Navigation("InventoryResults");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.ItemType", b =>
                {
                    b.Navigation("ItemTypeFieldSettings");

                    b.Navigation("LedgerItems");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.ItemUnit", b =>
                {
                    b.Navigation("ItemTypes");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.LedgerItem", b =>
                {
                    b.Navigation("InventoryResults");

                    b.Navigation("LedgerItemEvent");

                    b.Navigation("TagHistories");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.Location", b =>
                {
                    b.Navigation("InventoryResults");

                    b.Navigation("InventorySessions");

                    b.Navigation("LedgerItems");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.ProcessType", b =>
                {
                    b.Navigation("LedgerItemEvent");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.Tag", b =>
                {
                    b.Navigation("InventoryResults");

                    b.Navigation("TagHistories");
                });

            modelBuilder.Entity("sol_denka_stockmanagement.Database.TagActionType", b =>
                {
                    b.Navigation("TagHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
